### ISSUE TITLE
Offline search doesn't work

### ISSUE THREAD

**Issue by simo101** [tieniber/GridSearch#3]
When i try to use the offline search on 7.3.0 it throws an error. I tried the test project for 7.1.1 in this project and receive the same error. This error occurs when the constraint is added to filter the data.  Looking at the stacktrace on my mendix console i see the following error:

`com.mendix.core.CoreRuntimeException: Exception occurred in action '{"xpath":"//Appointments.Appointment[object Object]","amount":20,"offset":0,"returnsCount":true,"sort":[],"type":"RetrieveXPathSchemaRawAction"}', all database changes executed by this action were rolled back`

The error is thrown after the grid is reloaded. The new constraints are added on this line:

[https://github.com/tieniber/GridSearch/blob/master/src/GridSearch/widget/GridSearchOffline.js#L112](https://github.com/tieniber/GridSearch/blob/master/src/GridSearch/widget/GridSearchOffline.js#L112)

But perhaps this is the incorrect format for the objects?

I looked at the online version and the adding constrains is slightly different, so i am wondering whether the offline should use the same code as the online or not?

Regards
Simon

**Comment by Mocke44** [comment]
Im am encountering the same error as above, also using mendix 7.3.

Any feedback or work arounds would be greatly appreciated.

**Comment by tieniber** [comment]
Interestingly, this widget works in my test project an on my test offline mobile app. It does throw errors during online use, because it depends on the mobile device's offline database in order to function. It should probably be modified to work in online mode as well, but that's the cause.

@simo101 is planning to pull some mobile debugging info for me today, as he was able to reproduce the issue in an offline app and I cannot.

**Comment by tieniber** [comment]
Offline search has been removed since an official Mendix widget for it has been released.
