### ISSUE TITLE
Issue with GridSearch + pluggable widgets in 9.12.1 with list views (error)

### ISSUE THREAD

**Issue by MarkMellink** [tieniber/GridSearch#67]
We recently faced issues upgrading from Mendix 9.6.6 to Mendix 9.12.1. We were getting errors with our pluggable widget on one page. It took us a while to replicate this issue, but we finally found out it was being caused by the following combination:
* Mendix upgrade from 9.6.6 --> 9.12.1
* A pluggable widget with a widget container
* A list view being in the pluggable widget container
* And this Grid Search widget being on the page.

**Steps to replicate the issue:**
* Using Mendix 9.6.6, open a project or create a new empty project.
* Create or use any pluggable widget, with a widget property type, and add it to your application.
* Put a list view in the pluggable widget container.
* Download the Grid Search widget from the app store and add it to the project.
* Add the Grid Search widget to the page where you put the list view in the pluggable widget (it does not matter where on the page you put it).

**All should be fine now. You should be able to run the app just fine. Next steps:**
* Upgrade the project to 9.12.1 by opening the project in Mendix Studio Pro 9.12.1.

**Result:** Error in the app stating that the pluggable widget cannot contain widgets of type list view.
**Expected result:** No error, same functionality as in Mendix 9.6.6.

I have also filed a support ticket for this and added a .zip to help replicate the above for convenience. In the .zip there is:
* My widget source code (an empty pluggable widget, with a widget container property type)
* The widget .mpk (koalitix.ListViewContainerTest.mpk)
* A mendix project .mpk in version 9.6.6, which is an empty app with 1 page where the widget is loaded in + the Grid Search widget is loaded in. There is no error occurring here.
* A mendix project .mpk in version 9.12.1, which is the same app as above, but upgraded to 9.12.1. There is an error here.

This is preventing us from upgrading to 9.12.1 because we do need the Grid Search functionality and our custom pluggable widget (it's a core interface in our app).

So it would be great if someone has ideas for a solution. We are also happy to spend time building a solution ourselves (e.g. creating our own grid search functionality), but I'm not sure if that's possible with the current Pluggable Widget framework. If someone can point us in the right direction that would be great!

**Comment by tieniber** [comment]
The basis of this issue is that you cannot put a non-pluggable widget inside a pluggable widget

As of Mendix 9.5 or so, the list view can be either pluggable or non-pluggable (i.e., React or Dojo-based). Studio Pro decides which version to render based on the situation. For example, using List View Controls on a page with the list view causes the list view to render as the Dojo widget, because List View Controls requires the Dojo implementation of the list view in order to function. The same applies for GridSearch, and somewhere between 9.6 and 9.12, the R&D team added logic so Grid Search causes the same behavior as List View Controls (causing the List View to render as the Dojo widget)

So: Although you didn’t get an error in 9.6, Grid Search shouldn’t have worked properly. I'll plan to open the test project you shared to Support and try to understand what happens.

But the limitation remains: in order to Grid Search to work, List View must be rendered as a Dojo widget, which cannot live in a pluggable (React) widget’s container.

**Comment by tieniber** [comment]
I looked at the 9.6 test app, but it looks like the pluggable widget doesn't actually render the list view (which means Grid Search can't do anything). Even if the list view did render, we'd have the same problem though. The List View needs to render as a React widget, which Grid Search can't (and will never be able to) interface with.
